apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static2
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/static2"

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: db-volume
#spec:
#  storageClassName: local-storage
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/local-storage"



