apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-static2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: timescale-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: local-storage
#  resources:
#    requests:
#      storage: 5Gi

