apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/local-storage"



