apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/app-share"



