#
# Конфигурационный файл для сервера авторизации
# Расположение: /mnt/app-share/AUTHSERVER/config.yaml
#
http_server:
  httpsMode: "off"
  sslCert: "./config/ssl.cert"
  sslKey:  "./config/ssl.key"
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
user1:
  email: "user1@mail.ru"
  name: "User 1"
  password: "user1"
  payload: '{"hasura":{"x-hasura-allowed-roles":["dba","user"],"x-hasura-default-role":"user","x-hasura-user-id":"1"}}'
user2:
  email: "tom@gmail.com"
  name: "User Tom"
  password: '1qaz!QAZ1qaz'
  payload: '{"hasura":{"x-hasura-allowed-roles":["admin","user"],"x-hasura-default-role":"user","x-hasura-user-id":"2"}}'
user3:
  email: "ivan@mail.ru"
  name: "User Ivan"
  password: 'Topaz108_Chernov'
  payload: '{"hasura":{"x-hasura-allowed-roles":["manager","user"],"x-hasura-default-role":"user","x-hasura-user-id":"3"}}'
